name: clean images cache
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: syossan27/purge-github-readme-image@v1.0.0
        with:
          repository: ${github.repository}
          token: ${{ secrets.GITHUB_TOKEN }}